import Head from "next/head";
import Features from "../components/Features";
import HeroSection from "../components/HeroSection";
import How from "../components/How";
import Pricing from "../components/Pricing";

export default function Home() {
  return (
    <div className="mt-0 font-poppins ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection />
        <Features />
        <How />
        <Pricing />
      </main>
    </div>
  );
}
